package by.jwd.testsys.controller.command.ajax;

public enum AjaxCommandName {
    EDIT_USER, SHOW_QUESTION, SAVE_ANSWER, GET_TESTS, ASSIGN_TEST, GET_ASSIGNED_USERS, DELETE_ASSIGNMENT,
    SHOW_RESULT_DATA, DELETE_TEST,CREATE_TEST,CREATE_QUESTION_ANSWER,UPDATE_QUESTION,COMPLETE_TEST, NO_COMMAND;
}
