package by.jwd.testsys.controller.command.front;

public enum CommandName {
    SIGN_UP,SIGN_IN,SIGN_OUT, SHOW_TESTS_PAGE,SHOW_EXE_TEST_PAGE,SHOW_USER_ACCOUNT,CHANGE_LANGUAGE,GET_RESULT,
    DISPLAY_STATISTIC,ASSIGN_TEST,TESTS_RESULTS,SHOW_ADMIN_PANEL, GET_EDIT_TEST_PAGE,WRONG_REQUEST;
}
