package by.jwd.testsys.controller.command.front;

public enum CommandName {
    SIGN_UP,SIGN_IN,SIGN_OUT, SHOW_TESTS_PAGE,SHOW_EXE_TEST_PAGE,SHOW_USER_ACCOUNT,CHANGE_LANGUAGE,GET_RESULT,
    DISPLAY_STATISTIC, SHOW_USER_ASSIGNMENT,ASSIGN_TEST,WRONG_REQUEST;
}
